language: python
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
  - 3.6
  - 3.7
matrix:
  fast_finish: true
addons:
  firefox: latest-esr
services:
  - xvfb
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
before_script:
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_script:
# Firefox may have trouble saying goodbye.
# So kill it, but don't complain when it is not there.
  - pkill -9 firefox || true
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - guido.stevens@cosent.net
